import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { FormBuilder, FormGroup, FormControl, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { HotToastService } from '@ngxpert/hot-toast';
import { ClientCompanyService, ClientCompany } from '@app/core/services/client-company.service';
import { ClientService, CreateClientDto } from '@app/core/services/client.service';
import { finalize, catchError, of } from 'rxjs';

@Component({
  selector: 'app-contact-person-add',
  templateUrl: './contact-person-add.component.html',
  styleUrls: ['./contact-person-add.component.scss'],
  encapsulation: ViewEncapsulation.None,
  standalone: false,
})
export class ContactPersonAddComponent implements OnInit {
  userForm: FormGroup;
  isSubmitting = false;
  isLoadingClient = false;
  preSelectedClient: ClientCompany | null = null;
  clientId: number | null = null;

  // Gender options (matching user-add component)
  genderOptions = [
    { code: 'male', name: 'Herr' },
    { code: 'female', name: 'Frau' },
    { code: 'other', name: 'Divers' },
  ];

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private route: ActivatedRoute,
    private location: Location,
    private clientCompanyService: ClientCompanyService,
    private clientService: ClientService,
    private toast: HotToastService,
  ) {}

  ngOnInit(): void {
    this.initializeForm();
    this.loadClientFromRoute();
  }

  /**
   * Initialize the reactive form
   */
  private initializeForm(): void {
    this.userForm = this.fb.group({
      gender: ['', Validators.required],
      firstName: ['', [Validators.required, Validators.minLength(2)]],
      lastName: ['', [Validators.required, Validators.minLength(2)]],
      phone: ['', [Validators.pattern(/^[+]?\d{4,20}$/)]],
      email: ['', [Validators.required, Validators.email]],
      // Password is auto-generated by backend and sent via email
      customers: this.fb.group({}),
    });
  }

  /**
   * Load client from route parameter
   */
  private loadClientFromRoute(): void {
    this.route.params.subscribe((params) => {
      const clientIdParam = params['client'];
      console.log('🔍 Route client parameter:', clientIdParam);

      if (clientIdParam) {
        this.clientId = Number(clientIdParam);

        if (!isNaN(this.clientId)) {
          this.loadClientCompany(this.clientId);
        } else {
          console.error('❌ Invalid client ID in route:', clientIdParam);
          this.toast.error('Ungültige Kunden-ID', {
            position: 'bottom-right',
            duration: 3000,
          });
          this.location.back();
        }
      } else {
        console.log('ℹ️ No client parameter in route - creating contact without client assignment');
      }
    });
  }

  /**
   * Load specific client company by ID
   */
  private loadClientCompany(clientId: number): void {
    this.isLoadingClient = true;

    console.log('🔄 Loading client company with ID:', clientId);

    // Use getClientCompanies and filter for the specific client
    this.clientCompanyService
      .getClientCompanies(1, 100)
      .pipe(
        finalize(() => {
          this.isLoadingClient = false;
        }),
        catchError((error) => {
          console.error('❌ Error loading client companies:', error);

          this.toast.error('Fehler beim Laden des Kundenunternehmens', {
            position: 'bottom-right',
            duration: 4000,
          });

          return of(null);
        }),
      )
      .subscribe({
        next: (response) => {
          if (response && response.data) {
            // Find the specific client company by ID
            const clientCompany = response.data.find((company) => company.id === clientId);

            if (clientCompany) {
              console.log('✅ Client company loaded:', clientCompany);
              this.preSelectedClient = clientCompany;
              this.setupDynamicForm();
            } else {
              console.error('❌ Client company not found with ID:', clientId);
              this.toast.error('Kundenunternehmen nicht gefunden', {
                position: 'bottom-right',
                duration: 3000,
              });
              this.location.back();
            }
          } else {
            console.error('❌ No client companies data received');
            this.toast.error('Keine Kundenunternehmen gefunden', {
              position: 'bottom-right',
              duration: 3000,
            });
            this.location.back();
          }
        },
      });
  }

  /**
   * Setup form controls dynamically for the preselected client
   */
  private setupDynamicForm(): void {
    if (!this.preSelectedClient) return;

    const customersGroup = this.userForm.get('customers') as FormGroup;

    // Clear existing controls
    Object.keys(customersGroup.controls).forEach((key) => {
      customersGroup.removeControl(key);
    });

    // Add control for the preselected client and set it to true
    const controlName = this.getControlName(this.preSelectedClient.name);
    customersGroup.addControl(controlName, new FormControl(true));

    console.log('🎯 Dynamic form setup completed for client:', this.preSelectedClient.name);
  }

  /**
   * Convert company name to a valid form control name
   */
  getControlName(companyName: string): string {
    return companyName
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '') // Remove special characters
      .replace(/\s+/g, ''); // Remove spaces
  }


  /**
   * Check if form is valid for submission
   */
  isFormValidForSubmission(): boolean {
    // Form is valid if all fields are filled
    // Client assignment is now optional
    return this.userForm.valid;
  }

  /**
   * Get fallback image for companies without logos
   */
  getFallbackImage(companyName: string): string {
    const fallbacks: { [key: string]: string } = {
      luxottica: 'images/projects/p-1.png',
      woom: 'images/projects/p-2.png',
      hugendubel: 'images/projects/p-3.png',
      reebok: 'images/projects/p-4.png',
    };

    const key = companyName.toLowerCase();
    return fallbacks[key] || 'images/default-company-logo.png';
  }

  /**
   * Submit form and create client user
   */
  onSubmit(): void {
    console.log('Submit button clicked');
    console.log('Form valid:', this.userForm.valid);
    console.log('Preselected client:', this.preSelectedClient);
    console.log('Form value:', this.userForm.value);

    if (!this.isFormValidForSubmission() || this.isSubmitting) {
      console.log('❌ Form invalid or already submitting');

      this.userForm.markAllAsTouched();

      if (!this.userForm.valid) {
        this.toast.error('Bitte füllen Sie alle erforderlichen Felder korrekt aus', {
          position: 'bottom-right',
          duration: 3000,
        });
      }

      return;
    }

    this.isSubmitting = true;

    console.log('🚀 Starting client creation for contact person...');

    const formValues = this.userForm.value;

    // Create client data - include client company if pre-selected, otherwise create without assignment
    // Password will be auto-generated by backend and sent via email
    const createClientData: CreateClientDto = {
      email: formValues.email,
      // password is optional - backend will generate it automatically
      firstName: formValues.firstName,
      lastName: formValues.lastName,
      gender: formValues.gender,
      phone: formValues.phone,
      clientCompanies: this.preSelectedClient ? [{ id: this.preSelectedClient.id }] : [],
    };

    console.log('📤 Sending client creation request:', createClientData);

    // Show loading toast
    const loadingToast = this.toast.loading('Erstelle Ansprechpartner...', {
      position: 'bottom-right',
      duration: 2000,
    });

    this.clientService
      .createClient(createClientData)
      .pipe(
        finalize(() => {
          this.isSubmitting = false;
          loadingToast.close();
        }),
      )
      .subscribe({
        next: () => {
          console.log('✅ Contact person created successfully');

          // Get the email of the newly created contact (we'll use it to find the user)
          const newContactEmail = this.userForm.get('email')?.value;

          this.toast.success('Ansprechpartner wurde erfolgreich erstellt! Das Passwort wurde per E-Mail versendet.', {
            position: 'bottom-right',
            duration: 4000,
            icon: '✅',
          });

          // Check if we came from client-add page
          const navigation = this.router.getCurrentNavigation();
          const state = navigation?.extras?.state || (window.history as any).state;

          if (state?.returnTo && state?.formState) {
            // Navigate back to client-add with form state and new contact email
            setTimeout(() => {
              this.router.navigate([state.returnTo], {
                state: {
                  formState: state.formState,
                  newContactEmail: newContactEmail
                }
              });
            }, 1000);
          } else {
            // Navigate back to the previous page
            setTimeout(() => {
              this.location.back();
            }, 1000);
          }
        },
        error: (error) => {
          console.error('❌ Error creating contact person:', error);

          const errorMessage = this.getErrorMessage(error);
          this.toast.error(errorMessage, {
            position: 'bottom-right',
            duration: 5000,
            icon: '❌',
          });
        },
      });
  }

  /**
   * Extract user-friendly error message from error response
   */
  private getErrorMessage(error: any): string {
    if (error?.data?.errors) {
      const errors = error.data.errors;

      if (errors.email) {
        return 'Diese E-Mail-Adresse wird bereits verwendet.';
      }

      if (errors.clientCompanies) {
        return 'Das ausgewählte Kundenunternehmen wurde nicht gefunden.';
      }

      if (errors.user === 'unauthorizedUserType') {
        return 'Sie haben keine Berechtigung, Clients zu erstellen. Nur Akzente-Benutzer können Clients anlegen.';
      }

      const firstError = Object.values(errors)[0];
      return typeof firstError === 'string' ? firstError : 'Validierungsfehler in den Eingabedaten.';
    }

    if (error?.data?.message) {
      return error.data.message;
    }

    if (error?.message) {
      return error.message;
    }

    if (error?.status === 401) {
      return 'Unauthorized: Sie müssen als Akzente-Benutzer angemeldet sein.';
    }

    if (error?.status === 422) {
      return 'Ungültige Eingabedaten. Bitte überprüfen Sie Ihre Eingaben.';
    }

    if (error?.status === 500) {
      return 'Serverfehler. Bitte versuchen Sie es später erneut.';
    }

    return 'Ein unbekannter Fehler ist aufgetreten beim Erstellen des Ansprechpartners.';
  }

  /**
   * Cancel and navigate back
   */
  cancel(): void {
    this.toast.info('Vorgang abgebrochen', {
      position: 'bottom-right',
      duration: 2000,
    });

    this.location.back();
  }

  /**
   * Check if form field has error
   */
  hasFieldError(fieldName: string): boolean {
    const field = this.userForm.get(fieldName);
    return !!(field && field.invalid && (field.dirty || field.touched));
  }

  /**
   * Get field error message
   */
  getFieldError(fieldName: string): string {
    const field = this.userForm.get(fieldName);
    if (!field || !field.errors) return '';

    if (field.errors['required']) return `${fieldName} ist erforderlich`;
    if (field.errors['email']) return 'Ungültige E-Mail-Adresse';
    if (field.errors['minlength']) return `Mindestens ${field.errors['minlength'].requiredLength} Zeichen erforderlich`;
    if (field.errors['pattern']) return 'Ungültiges Format';

    return 'Ungültige Eingabe';
  }
}
